### ISSUE TITLE
Homepage: Incorrect font-weight for section title. It should be Light, not Regular

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Elysium-Functions#26]
![image](https://cloud.githubusercontent.com/assets/12888048/16186830/60765786-36ff-11e6-8b4e-a125e620eb95.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16186833/64150482-36ff-11e6-964f-ad6c6a20c734.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16186836/6980409e-36ff-11e6-84a8-bcbb5411954f.png)

**Comment by eltitan** [comment]
I forgot to leave a comment about this. I actually used the given font-weight on the design which is Light but the result is different compared to an actual page. I already revert the font-weight kindly check :)
